namespace io.Alliance.ADN.Semantic; 

public enum TokenType {
    KEYWORD_STRUCT,
    KEYWORD_ARR,
    KEYWORD_BOOL,
    KEYWORD_I8,
    KEYWORD_I16,
    KEYWORD_I32,
    KEYWORD_I64,
    KEYWORD_F32,
    KEYWORD_F64,
    KEYWORD_STR,
    
    TOKEN_BRACE_OPEN,
    TOKEN_BRACE_CLOSE,
    TOKEN_BRACKET_OPEN,
    TOKEN_BRACKET_CLOSE,
    TOKEN_EQUAL,
    TOKEN_COMMA,
    TOKEN_SEMICOLON,
    TOKEN_IDENTIFIER,
    
    LITERAL_TRUE,
    LITERAL_FALSE,
    LITERAL_NUMBER,
    LITERAL_FLOAT,
    LITERAL_STRING
}